# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

CONFIG_I2C=y
CONFIG_TRACKPOINT_I2C=y
CONFIG_TRACKPOINT_I2C_LOG_LEVEL_NONE=y
CONFIG_I2C_SHELL=y
CONFIG_INPUT=y
CONFIG_ZMK_INPUT_LISTENER=y
CONFIG_ZMK_POINTING=y
CONFIG_SHELL=y
CONFIG_KERNEL_SHELL=y
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y