manifest:
  remotes:
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: maged-william
      url-base: https://github.com/Maged-William
  projects:
    - name: zmk
      remote: badjeff
      revision: main
      import: app/west.yml
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: maged-william
      revision: stream-only-mode-fixed
  self:
    path: config
